controller_list:
  - name: fake_arm_controller
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
      - Joint_6
      - Joint_7
      - Joint_8
      - Joint_9
      - Joint_10
      - Joint_11
      - Joint_12
      - Joint_13
      - Joint_14
      - Joint_15
      - Joint_16
      - Joint_17
      - Joint_18
      - Joint_19
      - Joint_20